---
- name: Provision a network for running Magnolia on AWS
  hosts: local
  connection: local
  gather_facts: false
  roles:
    - {
        role: provision-vpc,
        aws_vpc_name: "raw-experimental-dev-vpc",
        aws_vpc_cidr: "172.31.0.0/16",
        aws_vpc_region: "eu-west-2",
        aws_vpc_description: "Test VPC for AW"
      }
    - {
        role: provision-subnet,
        aws_subnet_name: "raw-experimental-public-subnet-1",
        aws_subnet_cidr: "172.31.0.0/20",
        aws_subnet_description: "Magnolia public subnet 1 (experimental)",
        aws_subnet_region: "eu-west-2",
        aws_subnet_az: "eu-west-2a"
      }
    - {
        role: provision-subnet,
        aws_subnet_name: "raw-experimental-public-subnet-2",
        aws_subnet_cidr: "172.31.16.0/20",
        aws_subnet_description: "Magnolia public subnet 2 (experimental)",
        aws_subnet_region: "eu-west-2",
        aws_subnet_az: "eu-west-2b"
      }
    - {
        role: provision-subnet,
        aws_subnet_name: "raw-experimental-private-subnet",
        aws_subnet_cidr: "172.31.32.0/20",
        aws_subnet_description: "Magnolia private (experimental)",
        aws_subnet_region: "eu-west-2",
        aws_subnet_az: "eu-west-2b"
      }
