---
- name: Load AWS keys
  include_vars: "aws_keys.yml"

# - name: check that we can figure out the instance id
#   debug:
#     msg: "found ec2 instance {{ item.id }}"
#   with_items: "{{ ec2.instances }}"

- name: make images of EC2 instances
  ec2_ami:
    aws_access_key: "{{ magnolia_aws_access_key }}"
    aws_secret_key: "{{ magnolia_aws_secret_key }}"
    instance_id: "{{ item.id }}"
    region: "{{ item.region }}"
    name: "{{ aws_image_name }}-{{ aws_image_version }}-{{ aws_image_timestamp }}"
    wait: "{{ wait_until_available }}"
    tags:
      Name: "{{ aws_image_name }}"
      Timestamp: "{{ aws_image_timestamp }}"
      Service: "{{ aws_image_service }}"
      Version: "{{ aws_image_version }}"
  with_items: "{{ ec2.instances }}"
  register: image
