---
- name: Select Python 2.7 version
  become: true
  alternatives:
    name: python
    path: "{{ python_version }}"

- name: Install Java with yum
  become: true
  yum:
    name: "{{ java_version }}"
    state: present

- name: Select installed Java version
  become: true
  alternatives:
    name: java
    path: "{{ jre_version }}"
